// ng/src/app/app.component.ts
import { Component } from '@angular/core';
import { takeUntilDestroyed } from '@angular/core/rxjs-interop';
import { Material, Utils } from '@core';
import json from '@core/data.json';
import en from '@core/i18n/en.json';
import { Store } from '@ngrx/store';
import { TranslateService } from '@ngx-translate/core';
import {
  CutListActions,
  selectDescription,
  selectMaterials,
  selectTitle,
} from '@store';
import Printd from 'printd';
import { combineLatest } from 'rxjs';

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrl: './app.component.scss',
})
export class AppComponent {
  public description: string = '';
  public materials: Material[] = [];
  public title: string = '';

  constructor(
    private store: Store,
    private translate: TranslateService
  ) {
    this.translate.setTranslation('en', en);

    this.store.dispatch(CutListActions.parseJson({ json }));

    Utils.initPrintd(new Printd());

    combineLatest([
      this.store.select(selectTitle),
      this.store.select(selectDescription),
      this.store.select(selectMaterials),
    ])
      .pipe(takeUntilDestroyed())
      .subscribe(([title, description, materials]) => {
        this.title = title;
        this.description = description;
        this.materials = materials;
      });
  }

  public print(): void {
    Utils.printCutList(
      document.querySelector('.content-wrapper') as HTMLElement,
      [
        'h1, h2, li, .description, .material-stats, .project-name, .stats-col { color: black; }',
        '.section-name { color: white; }',
      ]
    );
  }
}

<main>
  <div class="content-wrapper">
    <ng-container *ngIf="title">
      <h1 class="mb-2">{{ title }}</h1>
    </ng-container>
    <ng-container *ngIf="description">
      <p class="description mb-4">{{ description }}</p>
    </ng-container>
    <div class="materials-wrapper">
      <ng-container *ngIf="materials">
        <ng-container *ngFor="let material of materials">
          <div class="material-wrapper">
            <app-material [material]="material"></app-material>
          </div>
        </ng-container>
      </ng-container>
    </div>
  </div>
  <div class="mt-4">
    <button onClick="print()">{{ 'print' | translate }}</button>
  </div>
</main>

// react/src/App.tsx
import {
  CutListData,
  Utils,
  selectDescription,
  selectMaterials,
  selectTitle,
} from '@cut-list-generator/core';
import * as data from '@cut-list-generator/core/data.json';
import Printd from 'printd';
import { useEffect } from 'react';
import { useTranslation } from 'react-i18next';
import { useSelector } from 'react-redux';
import './App.css';
import { MaterialComponent } from './components/Material';
import { parseJson } from './store/cutListSlice';
import { useAppDispatch } from './store/hooks';

function App() {
  const dispatch = useAppDispatch();

  const { t } = useTranslation();

  const title = useSelector(selectTitle);
  const description = useSelector(selectDescription);
  const materials = useSelector(selectMaterials);

  useEffect(() => {
    Utils.initPrintd(new Printd());

    dispatch(parseJson(data as CutListData));
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, []);

  const print = () => {
    Utils.printCutList(
      document.querySelector('.content-wrapper') as HTMLElement,
      [
        'h1, h2, li, .description, .material-stats, .project-name, .stats-col { color: black; }',
        '.section-name { color: white; }',
      ]
    );
  };

  return (
    <main>
      <div className="content-wrapper">
        {title && <h1 className="mb-2">{title}</h1>}
        {description && <p className="description mb-4">{description}</p>}
        <div className="materials-wrapper">
          {materials &&
            materials.map((material, i) => (
              <div className="material-wrapper" key={`material-${i}`}>
                <MaterialComponent material={material} />
              </div>
            ))}
        </div>
      </div>
      <div className="mt-4">
        <button onClick={print}>{t('print')}</button>
      </div>
    </main>
  );
}

export default App;
