// react/src/components/WoodStats.tsx
import { Wood } from '../../../core';

export interface WoodStatsComponentProps {
  wood: Wood;
}

const WoodStatsComponent = ({ wood }: WoodStatsComponentProps) => {
  return (
    <>
      <div className="wood-stats">
        {wood.stats.map((stat, i) => (
          <span key={`wood-stat-${i}`}>{stat}</span>
        ))}
      </div>
    </>
  );
};

export { WoodStatsComponent };

// ng/src/app/components/wood-stats/wood-stats.component.ts
import { Component, Input } from '@angular/core';
import { Wood } from '@core';

@Component({
  selector: 'app-wood-stats',
  templateUrl: './wood-stats.component.html',
  styleUrls: ['./wood-stats.component.scss'],
})
export class WoodStatsComponent {
  @Input()
  public wood!: Wood;
}

<div class="wood-stats">
  <ng-container *ngFor="let stat of wood.stats">
    <span>{{ stat }}</span>
  </ng-container>
</div>
