// react/src/components/Section.tsx
import { ChangeEvent, useState } from 'react';
import { Section } from '../../../core';
import { setSectionColor } from '../store/cutListSlice';
import { useAppDispatch } from '../store/hooks';

export interface SectionComponentProps {
  section: Section;
}

const SectionComponent = ({ section }: SectionComponentProps) => {
  const [bgColor, setBgColor] = useState<string>(section.color);

  const dispatch = useAppDispatch();

  const onChangeColor = (e: ChangeEvent<HTMLInputElement>) => {
    if (e.target.value) {
      const color = e.target.value;

      if (color) {
        dispatch(setSectionColor({ color, sectionId: section.id }));
        setBgColor(color);
      }
    }
  };

  return (
    <>
      <div
        className="section-name"
        id={`section-${section.id}`}
        style={{
          backgroundColor: bgColor,
        }}
      >
        <span>{section.name}</span>
        {
          <input
            type="color"
            value={bgColor}
            onChange={(e) => onChangeColor(e)}
            data-section-id={`section-${section.id}`}
          />
        }
      </div>
    </>
  );
};

export { SectionComponent };

// ng/src/app/components/section/section.component.ts
import { Component, Input } from '@angular/core';
import { Section } from '@core';
import { Store } from '@ngrx/store';
import { CutListActions } from '../../store/acions';

@Component({
  selector: 'app-section',
  templateUrl: './section.component.html',
  styleUrls: ['./section.component.scss'],
})
export class SectionComponent {
  @Input()
  public get section(): Section {
    return this._section;
  }
  public set section(value: Section) {
    this._section = value;
  }

  public get bgColor(): string {
    return this._bgColor ?? this.section.color;
  }

  private _bgColor!: string;
  private _section!: Section;

  constructor(private store: Store) {}

  public onChangeColor(event: Event): void {
    const color = (event.target as HTMLInputElement).value;
    if (color) {
      this._bgColor = color;

      this.store.dispatch(
        CutListActions.setSectionColor({
          params: { color, sectionId: this.section.id },
        })
      );
    }
  }
}

<div class="section-name" [ngStyle]="{ backgroundColor: bgColor }">
  <span>{{ section.name }}</span>
  <input type="color" [value]="bgColor" (change)="onChangeColor($event)" />
</div>
