// react/src/components/Material.tsx
import {
  Material,
  Project,
  Wood,
  selectMaterialProjects,
} from '@cut-list-generator/core';
import { useTranslation } from 'react-i18next';
import { useSelector } from 'react-redux';
import { SectionComponent } from './Section';
import { WoodComponent } from './Wood';
import { WoodStatsComponent } from './WoodStats';

export interface MaterialComponentProps {
  material: Material;
}

const MaterialComponent = ({ material }: MaterialComponentProps) => {
  const projects = useSelector(selectMaterialProjects(material.id));

  const { t } = useTranslation();

  const { totalCuts, totalLength } = material;

  return (
    <>
      <div
        className="material"
        id={`material-${material.id}`}
        key={`material-${material.id}`}
      >
        <h2>
          {material.name} ({material.length / 12}')
        </h2>
        <div className="material-stats">
          {t('numberOfCuts', { totalCuts, totalLength })}
        </div>
        <div className="material-stats">
          {t('numberOfWood', {
            woodLength: material.length / 12,
            woodCount: material.woodList.length,
            woodPercentage: (
              (totalLength / (material.length * material.woodList.length)) *
              100
            ).toFixed(2),
          })}
        </div>
        <div className="projects-wrapper">
          {projects && (
            <ol>
              {projects.map((project: Project, i: number) => (
                <li key={`project-${i}`}>
                  <div>
                    <p className="project-name">{project.name}</p>
                    <ol type="a">
                      {project.sections.map((section, j) => (
                        <li key={`section-${j}`}>
                          <SectionComponent section={section} />
                        </li>
                      ))}
                    </ol>
                  </div>
                </li>
              ))}
            </ol>
          )}
        </div>
        <div className="cutlist-wrapper">
          <div className="wood-col">
            {material.woodList.map((wood: Wood, i: number) => (
              <WoodComponent
                key={`wood-${i}`}
                materialId={material.id}
                wood={wood}
              />
            ))}
          </div>
          <div className="stats-col">
            {material.woodList.map((wood: Wood, i: number) => (
              <WoodStatsComponent key={`wood-stats-${i}`} wood={wood} />
            ))}
          </div>
        </div>
      </div>
    </>
  );
};

export { MaterialComponent };

// ng/src/app/components/material/material.component.ts
import { CommonModule } from '@angular/common';
import { Component, Input } from '@angular/core';
import { Material, Project, Wood } from '@core';
import { TranslateModule } from '@ngx-translate/core';
import { SectionComponent } from '../section/section.component';
import { WoodStatsComponent } from '../wood-stats/wood-stats.component';
import { WoodComponent } from '../wood/wood.component';

@Component({
  selector: 'app-material',
  templateUrl: './material.component.html',
  styleUrls: ['./material.component.scss'],
  standalone: true,
  imports: [
    CommonModule,
    TranslateModule,
    SectionComponent,
    WoodComponent,
    WoodStatsComponent,
  ],
})
export class MaterialComponent {
  @Input()
  public material!: Material;

  public get projects(): Project[] {
    return this.material?.projects ?? [];
  }
  public get woodList(): Wood[] {
    return this.material?.woodList ?? [];
  }
}

<div class="material">
  <h2>{{ material.name }} ({{ material.length / 12 }}')</h2>
  <div class="material-stats">
    {{ 'numberOfCuts' | translate: material }}
  </div>
  <div class="material-stats">
    {{
      'numberOfWood'
        | translate
          : {
              woodLength: material.length / 12,
              woodCount: material.woodList.length,
              woodPercentage: (
                (material.totalLength /
                  (material.length * material.woodList.length)) *
                100
              ).toFixed(2)
            }
    }}
  </div>
  <div class="projects-wrapper">
    <ng-container *ngIf="projects">
      <ol>
        <ng-container *ngFor="let project of projects">
          <li>
            <div>
              <p class="project-name">{{ project.name }}</p>
              <ol type="a">
                <ng-container *ngFor="let section of project.sections">
                  <li>
                    <app-section [section]="section"></app-section>
                  </li>
                </ng-container>
              </ol>
            </div>
          </li>
        </ng-container>
      </ol>
    </ng-container>
  </div>
  <div class="cutlist-wrapper">
    <div class="wood-col">
      <ng-container *ngFor="let wood of woodList">
        <app-wood [materialId]="material.id" [wood]="wood"></app-wood>
      </ng-container>
    </div>
    <div class="stats-col">
      <ng-container *ngFor="let wood of woodList">
        <app-wood-stats [wood]="wood"></app-wood-stats>
      </ng-container>
    </div>
  </div>
</div>
